# Generated by Django 5.1.4 on 2025-02-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RansomwareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_processes', models.TextField(blank=True, null=True)),
                ('detected_files', models.TextField(blank=True, null=True)),
                ('detected_connections', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
